name: wecoop_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  qr_flutter: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  html: ^0.15.0
  flutter_secure_storage: ^8.0.0
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.10
  flutter_dotenv: ^5.0.2
  badges: ^3.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  animations: ^2.0.6
  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.2
  google_fonts: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/app_icon.png
    - assets/images/wecoop_logo.png
    - assets/images/home/
